- .travis.yml
- CMakeLists.txt
- cmake/Modules/FindSphinx.cmake
- docs/CMakeLists.txt
- docs/manual/ddscxx.rst
- docs/manual/index.rst
- src/CMakeLists.txt
- src/ddscxx/CMakeLists.txt
- src/ddscxx/include/dds/core/detail/array.hpp
- src/ddscxx/include/dds/core/types.hpp
This PR adds a missing header `dds/core/detail/array.hpp` and build instructions. I've chosen to switch to Ubuntu 18.04 (as opposed to 16.04, which is used by Eclipse Cyclone DDS) and use both GCC 10 and Clang 10. I've also included the newest macOS target and a Windows target. The `.travis.yml` file is a little cleaner that the one in Eclipse Cyclone DDS (notice `GENERATOR` and `BUILD_TOOL_OPTIONS` exported in each platforms specific section), I'm planning to port those changes back to the example. Other than that, this PR adds support for building documentation. I've ported the `predoxygen.py` script in @ThijsSassen's [cdds-cxx](https://github.com/thijssassen/cdds-cxx) repository to CMake. I ported the script so that there's at least some documentation and we don't introduce yet another …
> Add buildfiles and missing header

- src/ddscxx/src/org/eclipse/cyclonedds/core/EntityDelegate.cpp
This makes the representation of the statuses in the result of status_changes() match the representation elsewhere in the C++ API. I'm not sure why there's a difference in representation between the C and the C++ API, but if there has be one, it should at least be consistent throughout.
> Convert status mask representation in status_changes

- CMakeLists.txt
- PackageConfig.cmake.in
- README.md
- examples/CMakeLists.txt
- examples/ddscxx_examples.rst
- examples/helloworld/CMakeLists.txt
- examples/helloworld/HelloWorldData.idl
- examples/helloworld/publisher.cpp
- examples/helloworld/readme.rst
- examples/helloworld/subscriber.cpp
This PR adds a proper CMake package config file and a helloworld example. Apart from that it also updates the README.md to be a little more in line with that of Eclipse Cyclone DDS and point to the correct repositories etc.
> Add CMake package confige, example and update README.md

- .travis.yml
- CMakeLists.txt
- cmake/Modules/CUnit.cmake
- cmake/Modules/CUnit/include/CUnit/Test.h
- cmake/Modules/CUnit/include/CUnit/Theory.h
- cmake/Modules/CUnit/src/main.c.in
- cmake/Modules/FindCUnit.cmake
- conanfile.txt
- src/ddscxx/CMakeLists.txt
- src/idlcxx/CMakeLists.txt
- src/idlcxx/include/idlcxx/cpp11backend.h
- src/idlcxx/include/idlcxx/idl_ostream.h
- src/idlcxx/include/idlcxx/streamer_generator.h
- src/idlcxx/include/idlcxx/version.h.in
- src/idlcxx/src/backendCpp11.c
- src/idlcxx/src/idl_ostream.c
- src/idlcxx/src/strdup.h
- src/idlcxx/src/streamer_generator.c
- src/idlcxx/tests/CMakeLists.txt
- src/idlcxx/tests/idl_ostream.c
- src/idlcxx/tests/streamer_generator.c
Created idlcxx library containing streamer generator functions.
The function idl_streamers_generate takes an idl_tree (the result of an idl file being parsed by the cyclonedds idl processor), and generates a number of functions.
For each C++ representation of each IDL object (as defined by the OMG C++11 language mapping) the following functions are generated:
- write_struct: takes a C++ IDL object and writes it in CDR representation to the supplied memory address
- write_size: takes a C++ IDL object and returns the number of bytes it would take up, if written in CDR representation
- read_struct: takes a C++ IDL object and a memory address and attempts to read the data at the address into the IDL object, assuming it is CDR formatted
Created idl_ostream to help with string …
> Idlcxx martijn

- src/ddscxx/include/dds/core/cond/TCondition.hpp
- src/ddscxx/include/dds/core/cond/TGuardCondition.hpp
- src/ddscxx/include/dds/core/cond/TStatusCondition.hpp
- src/ddscxx/include/dds/core/cond/detail/TConditionImpl.hpp
- src/ddscxx/include/dds/core/cond/detail/TGuardConditionImpl.hpp
- src/ddscxx/include/dds/core/cond/detail/TStatusConditionImpl.hpp
- src/ddscxx/include/dds/sub/cond/TQueryCondition.hpp
- src/ddscxx/include/dds/sub/cond/TReadCondition.hpp
- src/ddscxx/include/dds/sub/cond/detail/TQueryConditionImpl.hpp
- src/ddscxx/include/dds/sub/cond/detail/TReadConditionImpl.hpp
- src/ddscxx/include/dds/sub/detail/TDataReaderImpl.hpp
- src/ddscxx/include/dds/topic/detail/ContentFilteredTopic.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/core/cond/ConditionDelegate.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/core/cond/FunctorHolder.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/core/cond/GuardConditionDelegate.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/sub/cond/QueryConditionDelegate.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/sub/cond/ReadConditionDelegate.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/topic/TopicDescriptionDelegate.hpp
In this  pull request is one commit that modifies the way in which existing functors are passed (move to pass-by-value as apposed to pass-by-reference) to bring it more in line with common practice, and in anticipating of already agreed upon future changes to the OMG specification for this API.
The second commit is Cyclone specific, and allows you to set a filtering functor on the Delegate for the ContentFilteredTopic. This allows for content filtering based on for example lambda functions, as opposed to SQL expressions that Cyclone does not yet support.
Setting a filtering functor on a ContentFilteredTopic named "cft" may look like this:
cft->filter_function([](const Foo&sample)
{
return (sample.name() < "Dennis");
});
> Add support for application provided functors to do filtering on ContentFilteredTopics

- src/idlcxx/src/backendCpp11Type.c
- src/idlcxx/src/backendCpp11Utils.c
- src/idlcxx/src/idl_ostream.c
- src/idlcxx/src/streamer_generator.c
- src/idlcxx/tests/cpp11Backend.c
This PR basically changes every `node->identifier` dereference into `idl_identifier(node)` because every declaration now uses a `name` (location + identifier) for the benefit of better error reporting. Apart from that it also avoids reuse of the same `va_list` in one of the output functions.
> Adapt backed for scoping changes in libidl

- src/ddscxx/include/dds/sub/LoanedSamples.hpp
- src/ddscxx/include/dds/sub/cond/TQueryCondition.hpp
- src/ddscxx/include/dds/sub/cond/TReadCondition.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
- src/idlcxx/src/backendCpp11Type.c
- src/idlcxx/src/streamer_generator.c
- src/idlcxx/tests/cpp11Backend.c
- src/idlcxx/tests/streamer_generator.c
Fixing compiler warnings in compiled code and code generated from idl files:
- added missing copy assignment operators
- fixed doxygen code creating compiler warnings
Generated code quality of life fixes:
- no longer opening "empty" namespaces
- max key size immediately returns the "infinite size" number when one member has infinite size,
instead of calculating all previous and following members' maximum size as well
Number of bugfixes in serdata implementation, mainly related to calculating the hashes at the correct places
> Several fixes

- src/ddscxx/include/org/eclipse/cyclonedds/topic/TopicTraits.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
- src/idlcxx/include/idlcxx/backend.h
- src/idlcxx/src/backend.c
- src/idlcxx/src/backendCpp11Trait.c
- src/idlcxx/src/backendCpp11Type.c
- src/idlcxx/src/backendCpp11Utils.c
A new Trait function is now generated that determines whether a type
has keys or not. The outcome of this new function is now used to set
the is_keyed propery correctly.
Signed-off-by: Erik Hendriks <erik.hendriks@adlinktech.com>
> Fix issue where C++ topics would always be considered keyless.

- src/idlcxx/src/backendCpp11Utils.c
Simple changes to put quotes around generated string constants.
> Idlcxx const fixes

- src/ddscxx/include/dds/pub/detail/DataWriterImpl.hpp
- src/ddscxx/include/dds/sub/detail/TDataReaderImpl.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/pub/AnyDataWriterDelegate.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/sub/AnyDataReaderDelegate.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/topic/AnyTopicDelegate.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/topic/TopicTraits.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
- src/ddscxx/src/org/eclipse/cyclonedds/pub/AnyDataWriterDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/sub/AnyDataReaderDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/topic/AnyTopicDelegate.cpp
- src/idlcxx/src/streamer_generator.c
- src/idlcxx/tests/streamer_generator.c
In generated code, the vector is checked for emptyness before memcopying the container
Removed the use of c99 to c++ copy functions in datawriter/reader since these are no longer necessary
> Fixes for generated code and datawriter/reader

- src/ddscxx/include/dds/domain/TDomainParticipant.hpp
- src/ddscxx/include/dds/domain/detail/TDomainParticipantImpl.hpp
- src/ddscxx/include/dds/topic/detail/ContentFilteredTopic.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/domain/DomainParticipantDelegate.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/domain/DomainWrap.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/sub/AnyDataReaderDelegate.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/topic/TopicDescriptionDelegate.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
- src/ddscxx/src/org/eclipse/cyclonedds/domain/DomainParticipantDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/domain/DomainWrap.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/sub/AnyDataReaderDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/topic/TopicDescriptionDelegate.cpp
The PR builds on the [extended topic filter interface in Eclipse Cyclone DDS](https://github.com/eclipse-cyclonedds/cyclonedds/pull/606) and allows users to set alternative filter functions and filter on:
* sample
* sample and a user specified argument; or
* sampleinfo and a user specified argument; or
* sample, sampleinfo and a user specified argument
Next to that, this PR enables users to [set config programatically](https://github.com/eclipse-cyclonedds/cyclonedds/pull/604) from C++ by adding a DomainParticipant constructor that takes a `ddsi_config`.
@reicheratwork, if you would be so kind and review the changes, that'd be much appreciated.
> Extend ContentFilteredTopic and allow static configuration from C++

- src/ddscxx/include/dds/sub/detail/TDataReaderImpl.hpp
Remove the unnecessary static_cast to a TopicDescription
to a Topic type
> Fix issue with casting topicdescriptor to topic

- src/idlcxx/src/streamer_generator.c
- src/idlcxx/tests/CMakeLists.txt
- src/idlcxx/tests/generator/re_alignment_impl.cpp.in
- src/idlcxx/tests/streamer_generator.c
The re-alignment of writing data was not being done after
writing members containing sequences of lengths not known
at compile time
> Fix bug of re-alignment not being done after non-base members

- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
- src/idlcxx/src/streamer_generator.c
- src/idlcxx/tests/generator/bounded_sequence_impl.cpp.in
- src/idlcxx/tests/generator/bounded_sequence_of_structs_impl.cpp.in
- src/idlcxx/tests/generator/keys_union_implicit_impl.cpp.in
- src/idlcxx/tests/streamer_generator.c
- Fixed case indices not being generated for idl unions
- Fixed reading items beyond the bound for bounded sequences
- Fixed issue with take_cdr causing segmentation violations with take_cdr on empty keyless topics
> Fixes for unions and bounded sequences

- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
Fixes the initialization of the atomic sample pointer.
Without the direct initialization, we get the following error when compiling the HelloWorld example
```
use of deleted function ‘std::atomic<_Tp*>::atomic(const std::atomic<_Tp*>&) [with _Tp = HelloWorldData::Msg]’
: ddsi_serdata{}
^
```
> Fix atomic initialization of the sample pointer

- PackageConfig.cmake.in
I've been excitedly following the development of cyclonedds-cxx, and have been particularly interested in the development of the non-Java based idl compiler/generators since I have a somewhat irrational bias against Java. I compiled and installed cyclonedds and cyclonedds-cxx on the idlcxx branch to try it out. 
When building a HelloWorld-esqe test program, I ran into a problem where cmake would fail, complaining about not being able to find `idlcxx_generate`.
The change in this PR fixed the problem for me locally.
Thanks for your great work.
> Include idlcxx Generate.cmake file in PackageConfig.cmake.in.

- .azure/codecov.yml
- .azure/coverity-scan.yml
- .azure/templates/build-test.yml
- .codecov.yml
- CMakeLists.txt
- README.md
- azure-pipelines.yml
- cmake/Modules/Codecov.cmake
- cmake/Modules/Codecov/codecov.cmake
- cmake/Modules/FindGcov.cmake
- cmake/Modules/FindLcov.cmake
- cmake/Modules/Findcodecov.cmake
- cmake/Modules/llvm-cov-wrapper
- conanfile.txt
- examples/helloworld/CMakeLists.txt
- src/ddscxx/CMakeLists.txt
- src/ddscxx/include/dds/core/policy/TQosPolicyCount.hpp
- src/ddscxx/include/dds/core/policy/detail/TQosPolicyCountImpl.hpp
- src/ddscxx/include/dds/pub/detail/DataWriterImpl.hpp
- src/ddscxx/include/dds/sub/detail/TDataReaderImpl.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/topic/basic_cdr_ser.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/topic/cdr_stream.hpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/MiscUtils.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/topic/cdr_stream.cpp
- src/idlcxx/CMakeLists.txt
- src/idlcxx/src/generator.c
- src/idlcxx/src/streamers.c
- src/idlcxx/src/traits.c
- src/idlcxx/src/types.c
This PR adds build instructions for Azure Pipelines (including static analyzer checking (and fixes) for GCC, Clang-Tidy and the infamous random warning generator).
> Add support for Azure Pipelines and fix static analyzer warnings

- src/idlcxx/src/streamer_generator.c
- src/idlcxx/tests/CMakeLists.txt
- src/idlcxx/tests/generator/re_alignment_2_impl.cpp.in
- src/idlcxx/tests/generator/re_alignment_3_impl.cpp.in
- src/idlcxx/tests/generator/sequence_recursive_impl.cpp.in
- src/idlcxx/tests/streamer_generator.c
Removed "unknown" alignment state of -1 bytes, the "unknown"
alignment state is now 1 bytes
Re-alignment calculation+padding is now always done when the
alignment size increases, the new alignment is always set
Removed accumulated alignment calculation, since its gains
did not outweigh the increase in complexity
> Fix for cyclonedds-cxx/idlcxx issue #65

- examples/helloworld/CMakeLists.txt
- src/CMakeLists.txt
- src/ddscxx/CMakeLists.txt
- src/ddscxx/src/org/eclipse/cyclonedds/topic/cdr_stream.cpp
- src/idlcxx/Generate.cmake
- src/idlcxx/src/generator.c
- src/idlcxx/src/generator.h
- src/idlcxx/src/streamers.c
- src/idlcxx/src/traits.c
- src/idlcxx/src/types.c
* `idlcxx_generate` didn't add a dependency on the right target causing parallel Windows builds, like our CI builds, to fail.
* Aparently the cursor is always NULL in alignment of the CDR stream initially, or at least, it depends on the `add_zeroes` parameter. This PR corrects that.
* Union support depended on something not yet available in the IDL tree structure, namely the number of unused labels. [PR 784](https://github.com/eclipse-cyclonedds/cyclonedds/pull/784) in the *cyclonedds* repository fixes that. (until that one is merged, this PR will fail to build).
> Fix idlcxx_generate, make assert in alignment conditional and finish up unions

- .travis.yml
- src/ddscxx/include/org/eclipse/cyclonedds/topic/basic_cdr_ser.hpp
- src/idlcxx/src/generator.c
- src/idlcxx/src/streamers.c
- src/idlcxx/src/types.c
Improvements for the following:
- array declarators not being parsed correctly
- template streamers are more compatible with user-supplied container classes
- processing of typedefs
- safety of reading bounded sequences
- more descriptive exceptions thrown
- improved generated comparison operators for structs
- added generation of comparison operators for unions
> improvements to templated streaming

- src/ddscxx/include/dds/sub/detail/TDataReaderImpl.hpp
- Fixes #87
- Pass correct maximum number of samples to init_samples_buffers,
it will not exceed the size of the container the iterator belongs to
> DataReader with selector Forward iterator fix

- src/ddscxx/include/dds/sub/detail/SamplesHolder.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/sub/AnyDataReaderDelegate.hpp
- src/ddscxx/src/org/eclipse/cyclonedds/sub/AnyDataReaderDelegate.cpp
- src/ddscxx/tests/DataReader.cpp
Fix issue where filtered read/take may result in uninitialized SampleRefs for loans that are dimensioned to hold all available samples, not just the filtered ones. In cases where the loan is bigger than the number of matching samples, the destructor of the loan would crash on the uninitialized SampleRef objects.
> Fix issue where filtered read/take may result in a crash when returning loan

- .azure/templates/build-test.yml
- conanfile.txt
For some reason one specific build fails after I merged #88. I have a feeling it's an outdated cache or something because I couldn't reproduce it on an Ubuntu 20.04 machine locally, but we should drop CUnit and update GoogleTest anyway. The problem does not occur on my Azure Pipeline builds so this should fix the problem.
> Drop CUnit and update to GoogleTest 1.10.0

- .azure/coverity-scan.yml
This PR retains the Coverity build log for debugging. The C++ build does not suffer from the same problems as *cyclonedds*, but I couldn't figure out what exactly is wrong with it in a test repository. Perhaps it's the fact that it's mostly header files that do not result in object files but at this point I'm not really sure.
> Save Coverity build log for debugging

- .azure/coverity-scan.yml
- .azure/templates/build-test.yml
For some reason using GNU GCC is still problematic for C++ code. The same problem does not exist when using Clang.
> Switch Coverity Scan build to Clang

- src/idlcxx/src/generator.c
Includes for custom containers in templates types weren't added. This fixes #98.
> Visit type-spec in sequences too

- src/ddscxx/include/org/eclipse/cyclonedds/topic/TopicTraits.hpp
- src/idlcxx/src/generator.c
- src/idlcxx/src/generator.h
- src/idlcxx/src/streamers.c
- src/idlcxx/src/traits.c
- src/idlcxx/src/types.c
- move streaming functions to namespace org::eclipse::cyclonedds::core::cdr
- generated streaming functions for maximum size are now return immediately if they are of unbounded size
- streaming functions for typedefs avoid name clashes by adding the typedef namespace to the function name
- add the topic trait isSelfContained indicating whether the topic does not contain any pointers
- group the generated traits by namespace
> Generated isSelfContained trait and streaming fixes

- src/ddscxx/tests/CMakeLists.txt
- src/ddscxx/tests/EntityStatus.cpp
- src/ddscxx/tests/Listener.cpp
- src/ddscxx/tests/Util.cpp
- src/ddscxx/tests/Util.hpp
- src/ddscxx/tests/WaitSet.cpp
A shameless rip from the tests for ddsc in cyclonedds to ensure tests that require it use a unique topic name to avoid intermittent failures. Using the command `ctest -T test -R EntityStatus -j 4 --repeat until-fail:1000` didn't show any failure when testing locally whereas it failed 2 out of 3 times before. It's meant to be an addition to the work @reicheratwork did on #105 to ensure builds for PRs are reliable.
> Use unique topic name per test

- src/ddscxx/include/org/eclipse/cyclonedds/topic/TopicTraits.hpp
- src/idlcxx/src/generator.c
- src/idlcxx/src/generator.h
- src/idlcxx/src/traits.c
- src/idlcxx/src/types.c
* Include cstdint header if integer types or octets are used
* Include array header for anonymous arrays
* Include string header if string constants are used
* Include datatopic.hpp from TopicTraits.hpp
Fixes #108. @sumanth-nirmal, can you verify this fixes it for you?
Requires [PR 863 in cyclonedds](https://github.com/eclipse-cyclonedds/cyclonedds/pull/863) to be merged for the string constant issue.
> Add required headers to generated code

- src/ddscxx/include/dds/sub/detail/SampleRef.hpp
> Check for nullptr when accessing data with loaned samples

- src/idlcxx/src/streamers.c
- src/idlcxx/src/types.c
These two commits fix a generation issue in the type definitions and one in the generated serializer. Both deal with unions, both result in a uncompilable code.
> Fix idlcxx two backend bugs

- src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/basic_cdr_ser.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/cdr_stream.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
- src/ddscxx/tests/Bounded.cpp
- src/ddscxx/tests/CMakeLists.txt
- src/ddscxx/tests/Serdata.cpp
- src/ddscxx/tests/data/Serialization.idl
This fixes a number of issues in the CDR serialization, namely issues #115, #117 and #119:
- Alignment
- Byte Swapping on read side
and adds unittests to check for their correctness.
> Serialization fixes

- src/idlcxx/src/streamers.c
This forces the discriminant value to be the actual one read from the
CDR, not the default value associated with the setter we used.  E.g.:
union U switch (long) {
case 1: case 2: long a;
default: string b;
};
setting a value with a(...) will initialize the discriminant to 1, even
when the intended discrimant value is 2; the same problem exists with
the default case, as well as when where there is no "default:" but the
discrimant value doesn't map to any case.
Note that this fix is suboptimal: for the vast majority of the unions,
this doesn't come into play and this merely sets the discrimant value
the same value twice.
This fixes #128 according to the (improved and even nastier) https://gist.github.com/eboasson/62632a6fcfdde7839b3230856d205a38
> Always set the discrimant value to the one read

- src/idlcxx/src/streamers.c
- src/idlcxx/src/types.c
This fixes the setters (and initializers) for members that use type specifiers that are typedefs of base types or enumerators and fixes issues where the number of cases for setters suddenly changes. Still have to write tests, so put in draft mode.
> Fixes for issues with typedef of base types in type support generator

- docs/manual/idlcxx.rst
- src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/basic_cdr_ser.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/cdr_stream.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/cdr/cdr_stream.cpp
- src/ddscxx/tests/Bounded.cpp
- src/ddscxx/tests/DataReaderSelector.cpp
- src/ddscxx/tests/Serdata.cpp
- src/ddscxx/tests/data/Serialization.idl
- src/idlcxx/src/streamers.c
Improved CDR serialization performance by:
- only checking whether byte swaps need to be done at the start of serialization of the entire message, and then invoking the correct streaming function, in stead of checking for byte swapping at each primitive
- copying contiguous blocks of primitives (sequences/array) is now no longer done by iterating over each entry
Added unittests for serialization and byteswapping.
> Serialization improvements

- src/idlcxx/src/streamers.c
- src/idlcxx/src/types.c
This PR makes the `cyclonedds-cxx` compatible with the latest `cyclonedds`
Closes #154
> Make cyclonedds-cxx compatible with the changes for IDL in cyclonedds

- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
Please merge right after the merge of https://github.com/eclipse-cyclonedds/cyclonedds/pull/943
It seems that the cause of the shared memory unit test failure is due to the fact that use-iceoryx-custom-header is not yet merged on cyclonedds:master and therefore the header is in the wrong place. 
A rerun after the merge of cyclonedds:master should solve the issue.
> Integrate usage of iceoryx user header

- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
The latest changes to cyclonedds have added new functions to ddsi_sertype_ops
and these pointers must be explicitly initialized to not generate warnings
> Add missing ddsi_sertype_ops initializers

- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
- src/ddscxx/tests/SharedMemory.cpp
- src/ddscxx/tests/data/Serialization.idl
This PR adds support for dynamic types (linked sequences, strings both bounded and unbounded) with SHM and modifies the shared memory tests to test the same.
This is built on top of https://github.com/eclipse-cyclonedds/cyclonedds/pull/1000/ and the former needs to be merged before merging this.
Closes #165 
@eboasson @MatthiasKillat
> Update sertype interfaces to support dynamic types with SHM

- src/ddscxx/include/dds/sub/detail/SamplesHolder.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
- src/ddscxx/src/org/eclipse/cyclonedds/pub/AnyDataWriterDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/sub/AnyDataReaderDelegate.cpp
- src/ddscxx/tests/SharedMemory.cpp
This MR fixes the data path for `write_cdr`/`take_cdr` with SHM
1. With SHM enabled in `write_cdr`, when constructing the `serdata`, memory is loaned from `iceoryx` and copies the user-provided serialized data into this loaned memory and updates the `serdata` with the loaned chunk
2. While receiving the sample in the `CDRSamplesHolder` if the data is over iceoryx the data is taken from the iceoryx chunk, copied into the `CDRBlob` for the user, and the loaned chunk is released
Closes #175 
This should be merged after https://github.com/eclipse-cyclonedds/cyclonedds/pull/1031
> Fix write_cdr/take_cdr with SHM

- src/idlcxx/src/streamers.c
(Originally incorrectly referenced #157 which GitHub now desperately wants to close on merging this one.)
> Fix keylist processing for typedeffed topics

- src/ddscxx/include/dds/core/status/State.hpp
Even though `StatusMask` inherits from `std::bitset`, if you attempt to do
`StatusMask|StatusMask` it complains because the resulting type is
a bitset, not a StatusMask. Also the expected operator supported for
a StatusMask should be OR not bitshift that accumulates.
error: could not convert ‘std::operator|<32>(std::operator|<32>(std::operator|<32>(std::operator|<32>(dds::core::status::StatusMask::none(), dds::core::status::StatusMask::offered_deadline_missed()), dds::core::status::StatusMask::dds::core::status::StatusMask::liveliness_lost()), dds::core::status::StatusMask::publication_matched())’ from ‘std::bitset<32>’ to ‘dds::core::status::StatusMask’
> Add support for StatusMask | StatusMask

- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
- src/idlcxx/src/generator.c
- src/idlcxx/src/streamers.c
- src/idlcxx/src/types.c
Replace `idl_unalias` by `idl_strip` ([Cyclone DDS #1068](https://github.com/eclipse-cyclonedds/cyclonedds/pull/1068)) and update sertype ops (XTypes implementation [Cyclone DDS #904](https://github.com/eclipse-cyclonedds/cyclonedds/pull/904))
> Replace idl_unalias and update sertype ops

- CMakeLists.txt
To remain in sync with `cyclonedds` repository.
> Bump to 0.8.2

- src/ddscxx/CMakeLists.txt
- src/ddscxx/documentation.cmake
Like it says in the title. Doing it at build time saves some configure time and makes it so that changes to files don't require reconfiguration.
> Preprocess documentation input at build time

- examples/helloworld/CMakeLists.txt
- src/ddscxx/tests/CMakeLists.txt
- src/idlcxx/Generate.cmake
- src/idlcxx/src/generator.c
- src/idlcxx/src/streamers.c
- src/idlcxx/src/traits.c
In eclipse-cyclonedds/cyclonedds#989 a parameter is added to the IDLC `generate` function signature, and the configuration in `pstate` is moved to `.config`. This PR adds the parameter to the c++ generator function and updates the accessors for flags in pstate, and it adds the default-extensibility and (no-)warning option to the `idlcxx_generate` cmake function.
> IDLC generator config and default extensibility

- src/ddscxx/src/org/eclipse/cyclonedds/core/policy/PolicyDelegate.cpp
- src/ddscxx/tests/DataReader.cpp
An empty list of values for the data representation qos should not be set with dds_qset_data_representation when getting the C qos policy, to avoid overwriting the value that was implicitly set when creating the C entity.
> Fix for empty list of data representation qos values

- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
Each type gets its own specialised functions, and consequently the tkmap
hash table (in the core) will never consider two samples of different
types as equal.
The serdata hash is currently computed as the MD5 hash of the key value,
and so without mixing in "serdata_basehash" all samples with the same
key value end up with the same hash despite not comparing as equal.  In
other words, if there are many topics there are many hash collisions.
The "hopscotch" hash table used by tkmap blows up if it is fed too many
collisions.
Mixing in "serdata_basehash" addresses that problem.
Fixes #201 
> C++ serdata hash: mix in serdata_basehash

- src/ddscxx/include/dds/core/External.hpp
- src/ddscxx/tests/CMakeLists.txt
- src/ddscxx/tests/External.cpp
- src/ddscxx/tests/data/ExternalModels.idl
- src/idlcxx/src/generator.c
- src/idlcxx/src/generator.h
- src/idlcxx/src/streamers.c
- src/idlcxx/src/types.c
According to XTypes v1.3 7.5.1.2.3.3 added the dds::core::external
template class
Added unittests to test dds::core::external functionality
Added parsing of @external fields in generated C++ code
> Add external field handling

- src/ddscxx/src/org/eclipse/cyclonedds/core/cdr/fragchain.cpp
Address assert(false) / throwing of InvalidDataError exception with
"Fragchain contained fewer bytes than indicated size".
> Fix out-of-bounds check copying sample fragments

- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
- src/ddscxx/tests/Serdata.cpp
- src/ddscxx/tests/data/Serialization.idl
As keyless topics have the same key value each time, "calculating"
it can be short-circuited significantly
> Add skipping hashing of keyless topics

- src/ddscxx/include/org/eclipse/cyclonedds/topic/TopicTraits.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
The assignability check is removed from the sertype interface by https://github.com/eclipse-cyclonedds/cyclonedds/pull/1167. This commit removes the c++ implementation of this function
> Assignability check removed from sertype interface

- .gitignore
- examples/CMakeLists.txt
This commit fixes build error when trying to cross compile helloworld example:
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
CMake Error at examples/helloworld/CMakeLists.txt:19 (idlcxx_generate):
Unknown CMake command "idlcxx_generate".
Signed-off-by: Matija Tudan <tudan.matija@gmail.com>
> examples: fix build error when cross compiling examples

- src/ddscxx/tests/Regression.cpp
- src/ddscxx/tests/data/RegressionModels.idl
- src/idlcxx/src/generator.c
- src/idlcxx/src/streamers.c
- src/idlcxx/src/types.c
Added checking that the types supplied to the union container template class do not contain duplicates as std::variant can not handle this.
This fixes #127.
> Variant duplicate types fix

- src/idlcxx/src/generator.c
- src/idlcxx/src/generator.h
- src/idlcxx/src/streamers.c
- src/idlcxx/src/traits.c
Getting nestedness, and extensibility are in their own functions
Self-containedness functions are refactored
> Refactored a number of checks and utility functions

- src/idlcxx/src/streamers.c
In section 7.4.1.4.4.2.3 it states that the maximum number of enums
is 232, which is a typo for 2 to the 32nd power
Fixed the assumption that at most 232 enumerators will be encountered
in the generation of enumerator functions
> Fix for typo in IDLV4.0 spec

- .azure/templates/build-test.yml
- src/ddscxx/tests/CMakeLists.txt
- src/ddscxx/tests/SharedMemory.cpp
Fixes #224
This should be merged after https://github.com/eclipse-cyclonedds/cyclonedds/pull/1175
> Update to use iceoryx 2.0

- src/ddscxx/tests/Regression.cpp
- src/ddscxx/tests/data/RegressionModels.idl
- src/idlcxx/src/generator.c
- src/idlcxx/src/streamers.c
- src/idlcxx/src/types.c
A number of fixes related to array handling:
- added batch copying of primitive types in arrays which should improve performance
- fixed union cases not taking array declarators into account
- added unittests to check these additions
> Array fixes

- src/idlcxx/src/types.c
The C++ backend will give warnings when it encounters annotations
it does not support (yet):
- @try_construct
- @default_literal
> Add warnings for unsupported annotations

- src/ddscxx/tests/CMakeLists.txt
- src/ddscxx/tests/DataModels.cpp
- src/ddscxx/tests/data/CdrDataModels.idl
- src/idlcxx/src/generator.c
- src/idlcxx/src/generator.h
- src/idlcxx/src/types.c
Allows setting of default values in constructed types through the
@default annotation
At this point this only supports primitive non-enum types and strings
due to limitations in the idl parser
Add unittests to check whether this works as intended
> Add support for default parameters in constructors

- src/ddscxx/tests/Regression.cpp
- src/ddscxx/tests/data/RegressionModels.idl
- src/idlcxx/src/streamers.c
Arrays of unions/structs in union cases, did not retrieve the entity
properties for the streaming function, resulting in a failure to
compile
> Fix for arrays of unions/structs in union cases

- src/ddscxx/include/org/eclipse/cyclonedds/core/Missing.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/cdr/cdr_stream.cpp
Fixes problems with compiling under MSVC15 (2017)
- Changed check for TopicTraits::isKeyless in tokey function to inside function block, as this is a constexpr this will result in the same optimized bytecode, as MSVC15 seems to resolve the template classes (TopicTraits and datatopic in the wrong order)
- Added include for <algorithm> which MSVC15 could not find
> Fix issue 260

- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/cdr/basic_cdr_ser.cpp
- src/ddscxx/tests/CDRStreamer.cpp
- src/ddscxx/tests/Regression.cpp
- src/ddscxx/tests/data/RegressionModels.idl
This issue was caused by the to_key function to not stream the key
values correctly when encountering a type which had keys and required
xtypes functionality
The streaming operations (move/write) failed when they shouldnt and
the error was just being passed as a non-hashing of the key value
contents
Fixed the streaming of keys in this case, and the passing of failures
to stream in the to_key function
Added regression tests to check for the correct generation of keys in
this scenario
> Fix for issue #265

- src/ddscxx/tests/DataModels.cpp
- src/ddscxx/tests/data/CdrDataModels.idl
- src/idlcxx/src/generator.c
- src/idlcxx/src/types.c
The default value of enumerators will now also take the
@default_literal annotation into account when these enumerators are
used as members of structs
As, in C++, enum classes do not have default constructors, this
annotation does not have any effect here
> Add enumerator defaults to struct constructors

- examples/helloworld/readme.rst
Hey folks, this just fixes a small typo. The target names include `Helloworld`, not `HelloWorld`. This is correct earlier in the document; only these last two lines have the typo. Thanks!
> Fix a typo in the helloworld readme

- CMakeLists.txt
- examples/helloworld/readme.rst
- src/ddscxx/include/org/eclipse/cyclonedds/core/Missing.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/cdr/basic_cdr_ser.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/cdr/cdr_stream.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/cdr/extended_cdr_v2_ser.cpp
- src/ddscxx/tests/CDRStreamer.cpp
- src/ddscxx/tests/CMakeLists.txt
- src/ddscxx/tests/Regression.cpp
- src/ddscxx/tests/data/RegressionModels.idl
- src/ddscxx/tests/data/RegressionModels_pragma.idl
- src/idlcxx/src/streamers.c
- src/idlcxx/src/traits.c
This fixes:
* linker problems caused by the type object being defined in the header file
* a build issue with Visual Studio 2017
* issues compiling IDL: nested structures 
* key serialization for types requiring XCDR2
* some issues noted by Coverity (likely not affecting behaviour)
* a typo in the README
> Update to 0.9.1

- src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/basic_cdr_ser.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/cdr_stream.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/entity_properties.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/extended_cdr_v1_ser.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/extended_cdr_v2_ser.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/cdr/basic_cdr_ser.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/cdr/cdr_stream.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/cdr/entity_properties.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/cdr/extended_cdr_v1_ser.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/cdr/extended_cdr_v2_ser.cpp
- src/ddscxx/tests/GeneratedEntities.cpp
- src/ddscxx/tests/Regression.cpp
- src/idlcxx/src/generator.c
- src/idlcxx/src/streamers.c
This fixes issue #261
Improved the performance of (de)serialization through the following changes:
- flattened the entity_properties tree as the std::list approach was not that quick
- created a custom stack which is faster than std::stack
- moved adminstration of the streaming status of entity offset (e_off) and entity size (e_sz) out the entity_properties and into the streamer class
- added skipping of size determination through streaming functions when serialized type has constant size
- removed member start/stop checking for basic cdr streams
- simpified a number of frequently used streaming functions
- changed from a range based for-loop to just running over the bare pointers in get_type_props as this vector will not change in size
- removed a number of unnecessary checks for …
> Fix for issue #261

- src/ddscxx/include/org/eclipse/cyclonedds/topic/TopicTraits.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
- src/ddscxx/tests/CMakeLists.txt
- src/ddscxx/tests/TopicTypeDiscovery.cpp
- src/idlcxx/src/streamers.c
- src/idlcxx/src/traits.c
This PR fixes:
- issue #276 by replacing the scoped enumerator `std::memory_order::memory_order_release`  with its non-scoped alias `std::memory_order_release`
- issues uncovered by the newer builds of CycloneDDS which now supports topic/type discovery by default
- defining static members in template classes to contain the type/topic discovery information was not accepted by compilers other than GCC
- to work around this this data is now accessed by static accessor functions
- added unittests to check the correct generation of topic/type discovery information
@nate800 could you give this a try (and a review)?
> Fix issue 276 and type/topic discovery issues

- .azure/templates/build-test.yml
- PackageConfig.cmake.in
- src/idlcxx/Generate.cmake
We got missing boost include errors when testing the latest master in legacy C++11 mode. This PR should fix the issue and correctly declare Boost as a transitive dependency of CycloneDDS-CXX.
> Properly propagate dependency to Boost if ENABLE_LEGACY is true

- src/ddscxx/include/dds/pub/discovery.hpp
- src/ddscxx/include/dds/sub/discovery.hpp
This PR removes some scary wording from the C++ documentation that doesn't apply to Cyclone. Part of it is definitely OpenSplice-specific and overlooked until @thijsmie's improved formatting of the documentation. The bit about the `InstanceHandle` of discovery data may or may not coming from the OMG, but it just doesn't apply for us and so needs to be removed as well.
> Instance handles are well behaved in cyclone and discovery always takes place

- PackageConfig.cmake.in
The line has to be removed in order for projects to correctly
use CycloneDDS-CXX::ddscxx library when CycloneDDS-CXX was
built without idlcxx using the -DBUILD_IDLLIB=OFF option or
when crosscompiling (see commit 2050fc451555b8309d4ed5c02b948d8d1cfd4d8e).
Without idlcxx the Generate.cmake never gets installed in the
first place, so the usage of the PackageConfig file gives an error:
/usr/local/lib/cmake/CycloneDDS-CXX/CycloneDDS-CXXConfig.cmake:52 (include):
include could not find requested file:
/usr/local/lib/cmake/CycloneDDS-CXX/idlcxx/Generate.cmake
If idlcxx is being used, the include a few lines above with
if(TARGET CycloneDDS-CXX::idlcxx)
will bring in the necessary idlcxx_generate definition.
> PackageConfig: remove unconditional Generate.cmake include

- CMakeLists.txt
- README.md
- examples/helloworld/CMakeLists.txt
Support for EXPORT_PROPERTIES was added in CMake 3.12, so either the
minimum version required needs to be bumped, or this feature needs to be
emulated.  Ubuntu 22.04 ships with CMake 3.16, is over two years old now
and also the minimum required for ROS 2 Foxy, so that seems like a
reasonable new minimum version.
Closes #300 
> Bump minimum CMake version to 3.16

- src/ddscxx/include/org/eclipse/cyclonedds/core/cond/ConditionDelegate.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/core/cond/WaitSetDelegate.hpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/cond/ConditionDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/cond/GuardConditionDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/cond/StatusConditionDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/cond/WaitSetDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/sub/cond/ReadConditionDelegate.cpp
- src/ddscxx/tests/WaitSet.cpp
This MR changes the behavior of waitset to detach the conditions automatically when the conditions are closed or cleaned up.
Fixes #306
> Update waitset to detach conditions on cleanup

- src/ddscxx/src/org/eclipse/cyclonedds/core/cdr/entity_properties.cpp
The include for the C++ string library was missing, though this was not causing
issues in other compilation scenarioes, the order of compilation or parsing of
includes with Visual Studio 2017 caused this issue to be exposed
> Fix for issue #308

- src/idlcxx/src/traits.c
On failure generating the type info and type map, the code using these
blobs when writing out the traits would still free the typemap and
typeinfo blobs, even though the contents of the memory would be
undefined.  This changes the error handling so this is done only iff the
type info and type map were generated correctly.
> Free type map/info only if successfully generated

- src/ddscxx/src/org/eclipse/cyclonedds/pub/AnyDataWriterDelegate.cpp
The deprecated sertopic implementation is removed, see https://github.com/eclipse-cyclonedds/cyclonedds/pull/1397
> Remove unused include ddsi_sertopic.h

- src/ddscxx/src/org/eclipse/cyclonedds/sub/AnyDataReaderDelegate.cpp
- src/ddscxx/tests/CMakeLists.txt
- src/ddscxx/tests/SampleInfo.cpp
Setting the GenerationCount and Rank fields of the SampleInfo through the delegate did not copy the contents correctly, causing these fields to stay in the default constructed values (0)
Changed copying by calling the generation_count and rank setter functions
Added unittests to check for correct behaviour
> Fix bug in copying of GenerationCount and Rank in SampleInfo

- src/ddscxx/include/dds/core/cond/TWaitSet.hpp
- src/ddscxx/include/dds/domain/TDomainParticipant.hpp
- src/ddscxx/include/dds/pub/DataWriter.hpp
- src/ddscxx/include/dds/pub/TPublisher.hpp
- src/ddscxx/include/dds/sub/TDataReader.hpp
- src/ddscxx/include/dds/sub/TSubscriber.hpp
- src/ddscxx/include/dds/sub/cond/TQueryCondition.hpp
- src/ddscxx/include/dds/topic/TContentFilteredTopic.hpp
- src/ddscxx/include/dds/topic/TMultiTopic.hpp
- src/ddscxx/include/dds/topic/TTopic.hpp
- src/ddscxx/include/dds/topic/detail/ContentFilteredTopic.hpp
As the interface classes (DataWriter, Topic, DataReader, etc.) in the
C++ binding make liberal use of virtual inheritance, they can not be
inherited from in the normal sense, as calling the inherited
constructor in the derived constructor will cause the Reference class
contained within to be initialized before the derived constructor is
called, producing an exception
To this end, these interface classes are made final, which disables
inheriting from them
> Disable inheritance for interface classes

- src/idlcxx/src/generator.c
This issue was caused by the register_types function not looking
at the declarator in a typedef to see whether the arrays include
is required. When the typedef was used, then the include was
put in correctly.
The fix was to look at the declarators of typedefs by themselves
too.
> Fix for issue #293

- docs/manual/howto.rst
- docs/manual/howtos/exchange.rst
- docs/manual/howtos/listener.rst
- docs/manual/howtos/qos.rst
- docs/manual/howtos/status.rst
- docs/manual/howtos/waitset.rst
Added howto guides explaining the following basic DDS concepts:
- data exchange
- Quality of Service settings
- listeners
- waitsets
- statuses All guides are accompanied by code snippets giving examples of the use of the explained concepts
> Add howto guides for basic DDS concepts

- src/ddscxx/src/org/eclipse/cyclonedds/core/DDScObjectDelegate.cpp
Suppressing false positive reported by coverity
> Fix for coverity issue 398731

- src/ddscxx/include/org/eclipse/cyclonedds/topic/TopicTraits.hpp
Update typeinfo/typemap deser call because of a minor interface change in DDSI typelib, to be merged with https://github.com/eclipse-cyclonedds/cyclonedds/pull/1468
> Update typeinfo/typemap deserialize calls

- src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/fragchain.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/cdr/fragchain.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/pub/AnyDataWriterDelegate.cpp
Some name changes required because of refactoring of the DDSI interface
Related to https://github.com/eclipse-cyclonedds/cyclonedds/pull/1483
> Name changes related to DDSI interface refactoring

- src/ddscxx/include/org/eclipse/cyclonedds/domain/qos/DomainParticipantQosDelegate.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/pub/qos/DataWriterQosDelegate.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/pub/qos/PublisherQosDelegate.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/sub/qos/DataReaderQosDelegate.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/sub/qos/SubscriberQosDelegate.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/topic/qos/TopicQosDelegate.hpp
These functions were previously inline, and therefore did not need to be exported, but with commit 7b1f434 these are no longer inline and need to be exported for Windows compiles
Added exports for these functions now
> Added missing export of QoSPolicy non-const accessor functions

- src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/basic_cdr_ser.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/cdr_stream.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/entity_properties.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/extended_cdr_v1_ser.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/extended_cdr_v2_ser.hpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/cdr/basic_cdr_ser.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/cdr/cdr_stream.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/cdr/entity_properties.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/cdr/extended_cdr_v1_ser.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/cdr/extended_cdr_v2_ser.cpp
- src/ddscxx/tests/GeneratedEntities.cpp
- src/ddscxx/tests/Regression.cpp
- src/idlcxx/src/streamers.c
The type-specific entity_properties are now completely static, no longer thread_local
The getters for the entity_properties are also all const now, as the presence of struct fields is logged inside the streaming functions, and no modification of the member fields is necessary
@sumanth-nirmal, I can count on you to do a review of this PR?
> Fix for issue #326

- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
Incorrect encoding flag for xcdr_v1 appendable types was being required The read_header function was expecting the flag PL_CDR, but this should be PLAIN_CDR
> Fix for issue #336

- src/ddscxx/include/org/eclipse/cyclonedds/sub/SampleInfoImpl.hpp
This is a simple copy/paste error, and I forgot to change the second comparison parameter away from the first.
> Fix for coverity issue 73406

- docs/manual/idlcxx.rst
Minor edit to  apply cli formatting to the Sequences, Strings, Arrays and Unions sections
> CLI formatting added to idlcxx

- .azure/templates/build-test.yml
The default Conan version was updated to 2.0, so now we force fix the version to 1.59.0 as the current CUnit version (2.3.1) is currently not compatible with Conan v2.0
> Add fix for Conan update

- azure-pipelines.yml
- src/ddscxx/tests/Regression.cpp
- src/idlcxx/src/generator.c
- src/idlcxx/src/types.c
Removed deprecated pipelines (Ubuntu 18, macOS 10)
Added more modern pipelines (Ubuntu 22, macOS 11)
Fix uninitialized variable issues uncovered by analyzer
Disabled analyzer for Ubuntu GCC12 Debug builds
> Pipeline fixes

- .azure/templates/build-test.yml
- azure-pipelines.yml
- conanfile.txt
- src/ddscxx/include/dds/topic/detail/TTopicImpl.hpp
- src/ddscxx/tests/CMakeLists.txt
This makes it possible again to build without type/topic discovery support, and also adds a CI configuration to reduce the likelihood of this breaking again.
I've also bumped the boost version used on the CI, simply because I noticed that it was building the old version of boost from scratch and figured that the new version would be more likely to have binaries available for the updated set of platforms. (So far, so good.)
@reicheratwork my fix is not the most elegant because I completely disabled the "find topic" operation, but I think there are some cases that can be supported even when these parts of discovery are disabled. In the grand scheme of things, I think it is better to disable it altogether in this case than for it not to work at all, so I am in favour of merging this quickly …
> Fix build problem when type/topic discovery disabled

- src/ddscxx/include/dds/pub/detail/DataWriterImpl.hpp
- src/ddscxx/include/dds/sub/detail/TDataReaderImpl.hpp
- src/ddscxx/tests/CMakeLists.txt
- src/ddscxx/tests/DeferredDestruction.cpp
Add some fixes for lifetimes of entities not matching up with callback functions onto the same entities.
This causes issues like null dereferences and deadlocks.
This fix includes:
- reproducer for the issue
- ensurances that the lifetimes of entities are at least as long as the their callback functions
- listeners are present when callbacks are executed
This will not fix the entire issue, which lies at some choices made in the CycloneDDS-C layer.
If similar issues are still encountered, we advise to set the listener on an entity to `nullptr` before destroying it.
> Lifetime fix

- src/ddscxx/tests/SharedMemory.cpp
This updates the tests that interact directly with Iceoryx using the service names used for DDS topics to include the partition name, in accordance with the fix in the core repository for preventing cross-talk between DDS partitions when Iceoryx is used.
> Update SharedMemory test to include partition name

- src/ddscxx/include/dds/pub/detail/DataWriterImpl.hpp
- src/ddscxx/include/dds/sub/detail/TDataReaderImpl.hpp
- src/ddscxx/include/dds/topic/detail/TTopicImpl.hpp
- src/ddscxx/src/org/eclipse/cyclonedds/domain/DomainParticipantDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/pub/PublisherDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/sub/SubscriberDelegate.cpp
In case of a listener is passed to the constructor of an entity, the listener is expected to be set while creating the entity, otherwise, events happen between the entity creation and listener setting may get lost
> Fix for issue #378

- src/ddscxx/include/dds/pub/qos/detail/DataWriterQos.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/pub/qos/DataWriterQosDelegate.hpp
- src/ddscxx/src/org/eclipse/cyclonedds/pub/qos/DataWriterQosDelegate.cpp
This commit enables setting DurabilityService policy of DataWriterQos as described in OMG DDS v1.4 spec
> Fix for issue #389

- .azure/templates/build-test.yml
I thought the CI in #387 was failing because of a `CYCLONEDDS_BRANCH` variable being set only for building release branch, but not for a PR. It turns out that this is not the case and that it was using `master` all the time and I never noticed because there was no problem way back when.
Since I can't quickly figure out how to set it in Azure, this PR forces the correct branch of the `cyclonedds` repo to be built by changing the CI configuration files. It kinda makes sense that the CI configuration of the 0.10.x release branch of the C++ repo says it should use `releases/0.10.x` of the `cyclonedds` repository.
> Rely on release branch in CI

- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
The alignment bytes were calculated in the wrong manner, in stead of taking the remainder of a modulo 4 as the padding bytes, the modulo 4 of a remainder was used.
> Fix for wrong calculation of padding bytes in CDR header

- .github/codeql/resolved-misra-rules.yml
- .github/workflows/misra-regressions-check.yml
This PR adds a GitHub workflow for checking MISRA rule violations. It currently includes a check for MISRA rule 3.1 but more will be added as the code-base becomes more compliant.
See eclipse-cyclonedds/cyclonedds#1673 for the same PR included in the core Cyclone repository. The only major difference in is that the build for the code-base is manually specified in this workflow instead of being identified by auto-build ([misra-regressions-check.yml:64-71](https://github.com/eclipse-cyclonedds/cyclonedds-cxx/compare/master...NoxPardalis:cyclonedds-cxx:master?expand=1#diff-ff15e3d24fedce3faac6a63b42d98272ad5bb80ec6fbf00fddc6cd5ff1567e68R67-R71))
See #403 for the PR that solves the rules checked for by the workflow introduced within this PR.
> Add GitHub workflow for checking MISRA rule regressions

- src/ddscxx/src/org/eclipse/cyclonedds/pub/qos/DataWriterQosDelegate.cpp
- src/ddscxx/tests/Qos.cpp
The DurabilityService QoSPolicy was not being copied correctly when initializing a DataWriter QoS from a Topic QoS
This issue was missed as the DurabilityService policy of the DataWriter QoS was not being checked for its values in the unittests, this was also fixed
> Fix setting of DurabilityService policy in DataWriter QoS

- src/ddscxx/src/org/eclipse/cyclonedds/core/policy/PolicyDelegate.cpp
`org::eclipse::cyclonedds::core::convertByteSeq` allocates a new memory block, which is then copied via `dds_qset_userdata` but not freed afterwards.
> fix: avoid memleak when setting user data policy

- CMakeLists.txt
- src/ddscxx/include/dds/core/detail/ReferenceImpl.hpp
- src/ddscxx/include/dds/pub/detail/DataWriterImpl.hpp
- src/ddscxx/include/dds/sub/detail/TDataReaderImpl.hpp
- src/ddscxx/include/dds/topic/detail/TTopicImpl.hpp
This due to an error in the spec which is not due to be fixed until C++23
As CLang compiles with pedantic by default, the template signature warnings are now also included by default, these warnings are now suppressed, but only for CLang version>=12
This should also solve PR #187 without having code inside #ifdefs
> Removed superfluous template parameters

- src/idlcxx/Generate.cmake
- src/idlcxx/src/generator.c
The output directory parameter was not being used in when passed from idlc compiler to idlcxx library
Fixed so the output directory is now used in idlcxx
This should fix issue #413
@vecenyang : thanks for the suggested solution, can I rely on you to do a review of this PR?
> Added output directory to idlcxx

- examples/throughput/publisher.cpp
- examples/throughput/subscriber.cpp
Made the C++ throughput example program to be more in line with the expected output from the same example in CycloneDDS-C.
> Throughput example fixes

- src/ddscxx/include/dds/pub/detail/DataWriter.hpp
- src/ddscxx/include/dds/pub/detail/DataWriterImpl.hpp
- src/ddscxx/include/dds/sub/detail/DataReader.hpp
- src/ddscxx/include/dds/sub/detail/TDataReaderImpl.hpp
- src/ddscxx/include/dds/topic/detail/TTopicImpl.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/core/EntityDelegate.hpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/EntityDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/ListenerDispatcher.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/domain/DomainParticipantDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/pub/PublisherDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/sub/SubscriberDelegate.cpp
- src/ddscxx/tests/Listener.cpp
When creating an Entity with a Listener, any instantaneous events that occurred during creation would miss their callback. 
This was caused by the C++ API not being able to wrap the underlying C API with a C++ object prior to C already trying to invoking the callback. 
That is now resolved by not setting the Listener at creation time, but by setting it after successfully putting a C++ wrapper around the underlying C Entity.
This should fix issue #410
A prerequisite for applying this fix is to make sure pull request #https://github.com/eclipse-cyclonedds/cyclonedds/pull/1717 is applied to the cyclonedds repository.
> Fixed missing callbacks for pending events

- .azure/templates/build-test.yml
- CMakeLists.txt
- README.md
- azure-pipelines.yml
- conanfile.txt
- src/ddscxx/tests/DeferredDestruction.cpp
Companion to https://github.com/eclipse-cyclonedds/cyclonedds/pull/1767
> Eliminate Conan

- src/ddscxx/CMakeLists.txt
- src/ddscxx/include/dds/sub/TSampleInfo.hpp
- src/ddscxx/include/dds/sub/detail/LoanedSamples.hpp
- src/ddscxx/include/dds/sub/detail/Sample.hpp
- src/ddscxx/include/dds/sub/detail/SampleRef.hpp
- src/ddscxx/include/dds/sub/detail/SamplesHolder.hpp
- src/ddscxx/include/dds/sub/detail/TSampleInfoImpl.hpp
- src/ddscxx/include/dds/topic/detail/ContentFilteredTopic.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/sub/AnyDataReaderDelegate.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/sub/SampleInfoImpl.hpp
- src/ddscxx/src/org/eclipse/cyclonedds/sub/AnyDataReaderDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/sub/SampleInfoImpl.cpp
Clean up the C++ code to read/take samples from a DataReader by delegating them to the new dds_read/take_with_collector calls added to the C-API.
The old code base was using some dirty tricks to peek into the contents of the reader cache in order to allocate matching C++ resources, prior to the invocation of the regular dds_read/take calls of the underlying C-API. In order for the contents of the reader cache not to change in between the peek and the actual consumption of the data, the readercache lock would not be released by the peek operation and not be claimed by the dds_read/take operation (upon passing it a special value for the max_samples parameter). However, such a dirty trick goes against many coding conventions, and for that purpose a more flexible set of data accessor …
> Clean up the C++ code to read/take samples from a DataReader

- src/idlcxx/src/generator.c
This commit utilizes the MD5 hash for IDL source files and utilizes the result to generate a unique header guard macro when combined with the header file path.
Fixes: eclipse-cyclonedds/cyclonedds#1312
Requires: eclipse-cyclonedds/cyclonedds#1806
> Append IDL MD5 hash to create unique header guard

- .azure/templates/build-test.yml
- CMakeLists.txt
- README.md
- azure-pipelines.yml
- conanfile.txt
- src/ddscxx/include/dds/core/policy/CorePolicy.hpp
- src/ddscxx/include/dds/core/policy/TCorePolicy.hpp
- src/ddscxx/include/dds/core/policy/detail/CorePolicy.hpp
- src/ddscxx/include/dds/core/policy/detail/TCorePolicyImpl.hpp
- src/ddscxx/include/dds/pub/detail/DataWriter.hpp
- src/ddscxx/include/dds/pub/detail/DataWriterImpl.hpp
- src/ddscxx/include/dds/pub/qos/detail/DataWriterQos.hpp
- src/ddscxx/include/dds/sub/detail/DataReader.hpp
- src/ddscxx/include/dds/sub/detail/TDataReaderImpl.hpp
- src/ddscxx/include/dds/topic/detail/TTopicImpl.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/core/EntityDelegate.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/core/policy/PolicyDelegate.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/pub/qos/DataWriterQosDelegate.hpp
- src/ddscxx/src/dds/core/policy/CorePolicy.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/EntityDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/ListenerDispatcher.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/policy/PolicyDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/domain/DomainParticipantDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/pub/AnyDataWriterDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/pub/PublisherDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/pub/qos/DataWriterQosDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/sub/SubscriberDelegate.cpp
- src/ddscxx/tests/Listener.cpp
- src/ddscxx/tests/Qos.cpp
This backports
* #420 
* #406 
As well as #432 to get the CI back to life, though whether that was successful remains to be seen because of #406 and the build not using the correct branch of the `cyclonedds` repository.
It also bumps the version number to 0.10.4, I expect that doing a further patch release would appreciated.
> Some more backports to 010x

- src/ddscxx/include/dds/sub/detail/TDataReaderImpl.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/domain/DomainParticipantDelegate.hpp
- src/ddscxx/src/org/eclipse/cyclonedds/domain/DomainParticipantDelegate.cpp
- src/ddscxx/tests/Listener.cpp
When setting a Listener on the DomainParticipant that needs to handle events originating at a DataWriter, the application ignores (or crashes in debug mode) the Writer event when it occurs.
This was caused by the DomainParticipant class not overriding the default Listener callback handler set in the Entity class that was meant as an abstract placeholder and caused an assertion to fail.
That is now resolved by properly overriding this placeholder with a callback handler that properly propagates the callback to the appropriate function in the registered DomainParticipantListener.
This should fix issue #427
> Fix missing Writer callbacks on DomainParticipantListener

- examples/roundtrip/ping.cpp
- examples/roundtrip/pong.cpp
- examples/throughput/publisher.cpp
- examples/throughput/subscriber.cpp
- src/ddscxx/include/dds/sub/detail/TDataReaderImpl.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/core/ObjectDelegate.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/topic/CDRBlob.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/ObjectDelegate.cpp
- src/idlcxx/src/generator.c
- src/idlcxx/src/streamers.c
- src/idlcxx/src/types.c
Fixes for the following reported coverity issues:
- fun_call_w_exception
- copy_constructor_call
- dead_error_line
> Coverity fixes

- azure-pipelines.yml
Following this declaration:
https://github.com/actions/runner-images/issues/8263 updated the Ubuntu 22.04 clang pipelines to use clang(++) version 13 as Github only wants to support the latest 3 versions of clang, which are 13,14,15 starting 25.09.2023
> Fix clang to newer version in Ubuntu 22 pipelines

- src/ddscxx/tests/Regression.cpp
- src/ddscxx/tests/data/RegressionModels.idl
- src/idlcxx/src/streamers.c
- src/idlcxx/src/types.c
This fixes the issue of comparison operators not returning true for unions with default cases not associated with a type for said default case
Also added unittests for union comparison operators
This PR will fail the Ubuntu + Clang builds until this #458 PR has been merged.
@jordanLatta155 , could you give this one a look please?
> Fix issue #457

- src/ddscxx/include/dds/sub/detail/SamplesHolder.hpp
- src/ddscxx/tests/DataReader.cpp
... and incidentally address the
```
/home/vsts/work/1/s/src/ddscxx/include/dds/sub/detail/SamplesHolder.hpp:89:9: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
ddsi_serdata_to_ser_ref(sd, 0, ddsi_serdata_size(sd), &blob_content);
^~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
flagged by the CI in #480 but not caused by it. (It was caused by https://github.com/eclipse-cyclonedds/cyclonedds/pull/1947 adding the `warn_unused_result` attribute, and that's a good thing as it helped catch the bugs and the missing test.)
> Fix read_cdr and take_cdr

- .azure/templates/build-test.yml
- CMakeLists.txt
- README.md
- features.hpp.in
- src/ddscxx/CMakeLists.txt
- src/ddscxx/include/dds/core/QosProvider.hpp
- src/ddscxx/include/dds/core/detail/QosProvider.hpp
- src/ddscxx/include/dds/topic/detail/TTopicImpl.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/core/QosProviderDelegate.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/domain/qos/DomainParticipantQosDelegate.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/pub/qos/DataWriterQosDelegate.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/pub/qos/PublisherQosDelegate.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/sub/qos/DataReaderQosDelegate.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/sub/qos/SubscriberQosDelegate.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/topic/qos/TopicQosDelegate.hpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/QosProviderDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/policy/PolicyDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/domain/qos/DomainParticipantQosDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/pub/qos/DataWriterQosDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/pub/qos/PublisherQosDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/sub/qos/DataReaderQosDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/sub/qos/SubscriberQosDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/topic/AnyTopicDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/topic/qos/TopicQosDelegate.cpp
- src/ddscxx/tests/CMakeLists.txt
- src/ddscxx/tests/QosProvider.cpp
Add QosProvider functionality to C++ in accordance with the work done for https://github.com/eclipse-cyclonedds/cyclonedds/pull/1955.
> Implement QosProvider for C++ API.

- src/ddscxx/CMakeLists.txt
- src/ddscxx/include/dds/pub/detail/DataWriterImpl.hpp
- src/ddscxx/include/dds/sub/detail/TDataReaderImpl.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/core/NoopListener.hpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/ListenerDispatcher.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/NoopListener.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/domain/DomainParticipantDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/pub/PublisherDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/sub/SubscriberDelegate.cpp
The C++ code first installs a no-op listener in the entity, then completes construction of the C++ object and only then sets the application listener.  The dds_set_listener operation then invokes the listeners for any events that happened before the application listener was installed.
This is different from not installing a no-op listener: if there is no listener, an event is propagates up the entity hierarchy, checking whether any of those has a listener installed.  If there is one, it is invoked and the event is considered handled, and the status flag cleared (leaving no trace of the event).  If the application is trying to install a listener for the event, then this results in invoking the wrong listener.
Cyclone offers a mode in which the status flag is not cleared.  This means one …
> Fix UAF on listener arg on event during enable()

- CMakeLists.txt
- examples/CMakeLists.txt
- examples/helloworld/CMakeLists.txt
- examples/roundtrip/CMakeLists.txt
- examples/throughput/CMakeLists.txt
This sets RUNPATH (same as in [eclipse-cyclonedds/cyclonedds](https://github.com/eclipse-cyclonedds/cyclonedds) so the runtime linker can use it to find dependent libraries (like `libddsc`) when they are installed to the same directory as the C++ library.
Also found and fixed some typo's which caused the roundtrip example to not be correctly installed.
> Set RUNPATH in installed targets and fix roundtrip example install

- src/ddscxx/src/dds/core/Time.cpp
- src/ddscxx/tests/Time.cpp
This stops throwing the C++ wrapper from throwing an exception in the dds:core::Time class on trying to construct a time stamp prior to the 00:00:00 UTC on 1 January 1970. There is no reason to do that and it makes it vulnerable to receiving samples with earlier time stamps.
It is tricky to test: Cyclone won't allow writing these. I've tested it in a rather convoluted manner by hand ...
> Do not throw an exception on times before 19700101

- src/ddscxx/src/org/eclipse/cyclonedds/core/DDScObjectDelegate.cpp
The cyclone dds_entity associated with an CXX Entity must be deleted when the close on that entity is called
> delete associated dds_entity in DDScObjectDelegate.close

- src/idlcxx/src/generator.c
The external annotation is applied to (struct/union) members in IDL, so the check for this should be part of the iteration over the members.
> Fix self-contained check for aggregated type members

- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
Companion to https://github.com/eclipse-cyclonedds/cyclonedds/pull/2085
> Update/fix `get_serialized_size`

- src/ddscxx/tests/QosProvider.cpp
The following compilation error was generated on RedHat platforms with older gcc compilers (e.g. gcc8.4) when compiling with the  -Werror=sign-conversion:
"conversion to 'unsigned int' from 'int' may change the sign of the result"
This was caused by an implicit promotion to int32_t from the result of a logical AND operator on an unsigned char with a uint32_t as the mask. A subsequent logical OR on this result with an unsigned char shifted by four bits would cause the signed/unsigned conflict. By making sure all parameters are promoted to type int, we avoid this situation.
> Fix compilation error on RedHat when compiling with -Werror=sign-conversion

- CMakeCPack.cmake
Sister PR: https://github.com/eclipse-cyclonedds/cyclonedds/pull/2121
Cpack enforces architecture debian architecture i386 or amd64 even when compiling for arm64.
Now the architecture is detected by dpkg as per the standard debian process:
https://github.com/Kitware/CMake/blob/f3f9ad9499526963a46c10733ab9e8b3c0ebfcb1/Modules/Internal/CPack/CPackDeb.cmake#L541
> Support all debian architectue in cpack 

- src/ddscxx/tests/Regression.cpp
- src/ddscxx/tests/data/RegressionModels.idl
- src/idlcxx/src/types.c
Accessing std::variant by index means the type list for the variant doesn't have to be de-duped, saving a chunk of logic and ensuring bounded and unbounded strings can be mixed in unions with no problems.
Preserve access by type for use with boost::variant, where it is the only option.
> Switch union std::variant access to being by index

- CMakeLists.txt
- PackageConfig.cmake.in
- src/idlcxx/CMakeLists.txt
matched the behavior with cyclonedds
> Fix for cross compiling examples

- src/ddscxx/src/org/eclipse/cyclonedds/sub/AnyDataReaderDelegate.cpp
In the last PR i fixed it for `matched_subscriptions` but forgot `matched_publications` .. sorry, so here it is :)
> fix potential invalid instance handle for matched_publications

- src/ddscxx/include/dds/core/detail/TInstanceHandleImpl.hpp
- src/ddscxx/tests/Condition.cpp
- src/ddscxx/tests/Conversions.cpp
- src/ddscxx/tests/DataReader.cpp
- src/ddscxx/tests/DataReaderManipulatorSelector.cpp
- src/ddscxx/tests/DataWriter.cpp
- src/ddscxx/tests/DomainParticipant.cpp
- src/ddscxx/tests/FindDataReader.cpp
- src/ddscxx/tests/FindDataWriter.cpp
- src/ddscxx/tests/FindTopic.cpp
- src/ddscxx/tests/ListenerStress.cpp
- src/ddscxx/tests/Publisher.cpp
- src/ddscxx/tests/Qos.cpp
- src/ddscxx/tests/Query.cpp
- src/ddscxx/tests/Regression.cpp
- src/ddscxx/tests/Subscriber.cpp
- src/ddscxx/tests/Topic.cpp
- src/ddscxx/tests/Util.hpp
This PR removes a ambiguous operator.
It solves the following situation.
```cpp
dds::core::InstanceHandle handle = domainParticipant.instance_handle();
std::ostringstream s;
s << handle;
```
Error:
```
error C2593: 'operator <<' is ambiguous 
D:\conan\short\f72057\1\include\ddscxx\dds/core/detail/TInstanceHandleImpl.hpp(105,22): message : could be 'std::ostream &operator <<( 
std::ostream &,const dds::core::TInstanceHandle<org::eclipse::cyclonedds::core::InstanceHandleDelegate> &)' [found using argument-depe 
ndent lookup]
D:\conan\short\f72057\1\include\ddscxx\dds/core/detail/TInstanceHandleImpl.hpp(112,22): message : or       'std::ostream &operator <<( 
std::ostream &,const dds::core::TInstanceHandle<org::eclipse::cyclonedds::core::InstanceHandleDelegate>)' [found using argument-depend …
```
> remove ambiguous operator

- src/ddscxx/tests/Qos.cpp
Added the invalidPSMXInstances QoSPolicy test
Now using the maximum number of psmx instances as set in dds_psmx.h
> Re-add invalidPSMXInstances Qos test

- src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/cdr_stream.hpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/cdr/extended_cdr_v1_ser.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/cdr/extended_cdr_v2_ser.cpp
- src/ddscxx/tests/Regression.cpp
- src/ddscxx/tests/data/RegressionModels.idl
Fields which have a length header in XCDR were not skipping the cursor of the stream to the position indicated by the length field in the preceding header, this is fixed
Added tests to check whether this works as intended
> Fixes an issue with non-final fields not being finished correctly

- src/ddscxx/include/dds/core/policy/CorePolicy.hpp
- src/ddscxx/include/dds/core/policy/PolicyKind.hpp
- src/ddscxx/include/dds/core/policy/TCorePolicy.hpp
- src/ddscxx/include/dds/core/policy/detail/CorePolicy.hpp
- src/ddscxx/include/dds/core/policy/detail/TCorePolicyImpl.hpp
- src/ddscxx/include/dds/pub/qos/detail/DataWriterQos.hpp
- src/ddscxx/include/dds/sub/qos/detail/DataReaderQos.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/core/policy/Policy.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/core/policy/PolicyDelegate.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/pub/qos/DataWriterQosDelegate.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/sub/qos/DataReaderQosDelegate.hpp
- src/ddscxx/src/dds/core/policy/CorePolicy.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/policy/PolicyDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/pub/qos/DataWriterQosDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/sub/qos/DataReaderQosDelegate.cpp
- src/ddscxx/tests/Qos.cpp
This adds Cyclone's "ignore local" QoS setting to the C++ API. Fixes #139.
Something strikes me as odd, and that's that adding a very simple QoS policy to what is no more than a C++ wrapper around the C API touches 10 files/+275/-12 lines. The original introduction of the policy in Cyclone (that is, API *and* implementation) touched 5 files/+103 lines (https://github.com/eclipse-cyclonedds/cyclonedds/commit/4778d6c5dfb6853f07f81ac59ae0d65afc5e3c93).
Maybe I did something wrong, I don't know. @e-hndrks, perhaps you can have a look?
> Add IgnoreLocal reader, writer QoS setting

- src/ddscxx/include/dds/core/TQosProvider.hpp
- src/ddscxx/include/dds/core/detail/TQosProviderImpl.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/core/QosProviderDelegate.hpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/QosProviderDelegate.cpp
- src/ddscxx/tests/QosProvider.cpp
For compatibility purpose reduce QosProvider init/access variants to strict format (for init: `<lib>::<profile>` and for access: `<optional name>`).
> [!IMPORTANT]
> some of the new added tests rely on changes from: https://github.com/eclipse-cyclonedds/cyclonedds/pull/2287/commits/4e3d8f1b7ffea3bb6a99e37a0036db67a186192b
> of course this tests will fail until cyclonedds@master updates
> `fix:` restrict init/access scope of QosProvider.
