eclipse-cyclonedds/cyclonedds-cxx

- README.md
Signed-off-by: Thijs Sassen <thijs.sassen@adlinktech.com>
> Add Travis and Coverity badges to the Readme

- .travis.yml
This PR adds a Travis job for Coverity Scan
> Add Coverity Scan

- src/idlcxx/src/idl_ostream.c
- src/idlcxx/src/streamer_generator.c
- src/idlcxx/tests/streamer_generator.c
- file filtering is now no longer done on namespaces/modules, since these can be reopened in multiple files
- bug fix in flush_ostream function
- rewrote sequence implementation
> Several fixes

- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
@reicheratwork if you could spare a couple of minutes to look at this PR, that'd be great.
> Correct license header and fix some old-style-cast warnings

- src/ddscxx/src/org/eclipse/cyclonedds/sub/AnyDataReaderDelegate.cpp
- src/idlcxx/include/idlcxx/backendCpp11Utils.h
- src/idlcxx/src/backendCpp11Type.c
- src/idlcxx/src/backendCpp11Utils.c
Additional container customizability
Fix for issue with read operations
> Fix for read bug and improved container functionality

- src/idlcxx/src/backendCpp11Type.c
- src/idlcxx/src/backendCpp11Utils.c
- src/idlcxx/tests/cpp11Backend.c
These bugs were causing the idl compiler to crash.
> Fix several bugs in algorihm that tries to establish lowest unused discriminator value of a union.

- src/ddscxx/include/dds/sub/LoanedSamples.hpp
- src/ddscxx/include/dds/sub/SampleRef.hpp
- src/ddscxx/include/dds/sub/TDataReader.hpp
- src/ddscxx/include/dds/sub/TSampleRef.hpp
- src/ddscxx/include/dds/sub/detail/LoanedSamples.hpp
- src/ddscxx/include/dds/sub/detail/SampleRef.hpp
- src/ddscxx/include/dds/sub/detail/SamplesHolder.hpp
- src/ddscxx/include/dds/sub/detail/TDataReaderImpl.hpp
- src/ddscxx/include/dds/sub/detail/TSampleRefImpl.hpp
- src/ddscxx/include/dds/sub/detail/ddssub.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/sub/AnyDataReaderDelegate.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
- src/ddscxx/src/org/eclipse/cyclonedds/sub/AnyDataReaderDelegate.cpp
Signed-off-by: Erik Hendriks <erik.hendriks@adlinktech.com>
> Implement a zero-copy mechanism for loaned read/take calls.

- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
Multiple deserialization is prevented by:
- the getT() calls no longer are preceded by deserialization of
the data, since that already happens in the getT call
- added a separate setT function which creates the correct sample
in-place without having to deserialize the data as with getT, allowing
skipping of one deserialization step
@sumanth-nirmal @e-hndrks : could you check whether this works as expected and that I did not forget anything?
> Fix for cyclonedds-cxx/idlcxx issue #70

- docs/manual/idlcxx.rst
- src/idlcxx/src/generator.c
- src/idlcxx/src/generator.h
- src/idlcxx/src/streamers.c
- src/idlcxx/src/types.c
- Keylist parsing take correct stream functions for keyed members
- Improve swap functionality for unions structs and enums
> Idl keylist parsing

- src/idlcxx/src/generator.c
Signed-off-by: Jeroen Koekkoek <jeroen@koekkoek.nl>
> Use original filename for sources from additional directories

- src/ddscxx/src/org/eclipse/cyclonedds/domain/DomainParticipantDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/sub/cond/QueryConditionDelegate.cpp
- src/ddscxx/tests/Conversions.cpp
- src/ddscxx/tests/DataReader.cpp
- src/ddscxx/tests/DataReaderManipulatorSelector.cpp
- src/ddscxx/tests/DataReaderSelector.cpp
- src/ddscxx/tests/FindTopic.cpp
- src/ddscxx/tests/Listener.cpp
Fixes for to get previously disabled unittests working, separated by type.
After the sub-commits are approved, will merge them into 1 or 2 commits and then create a real PR.
> Unittest fixes

- src/idlcxx/src/streamers.c
> Fix resolution of streaming functions with sequence of bools

- src/idlcxx/src/streamers.c
> Fix the check for bool type in streamer

- src/ddscxx/include/dds/core/policy/TCorePolicy.hpp
- src/ddscxx/include/dds/core/policy/detail/TCorePolicyImpl.hpp
> Added Liveliness Automatic convenience function with lease_duration paramter.

- src/ddscxx/include/dds/sub/detail/TDataReaderImpl.hpp
This PR simply fixes a wrong description in the doc.
> Fix the doc of 'dds::sub::detail::DataReader<T>::init'

- .azure/templates/build-test.yml
- CMakeLists.txt
> Bump version for development branch

- .azure/templates/build-test.yml
- azure-pipelines.yml
Match versions so 0.8.x builds on CI.
> Pin cyclonedds-cxx 0.8.x to cyclonedds 0.8.x

- src/ddscxx/tests/WaitSet.cpp
This MR adds a simple test to verify if the status conditions attached to waitset trigger as expected.
> Add test for checking if the status conditions trigger correctly

- src/idlcxx/CMakeLists.txt
See discussion on https://github.com/eclipse-cyclonedds/cyclonedds/issues/952
> Rename libidlcxx to libcycloneddsidlcxx

- docs/manual/conf.py
Equivalent change as [cyclonedds#1114](https://github.com/eclipse-cyclonedds/cyclonedds/pull/1114).
> Fix windows docs build

- CMakeLists.txt
- README.md
> Match CMake version with cyclonedds

- src/ddscxx/tests/SharedMemory.cpp
> Drop removed configuration settings from shm test

- src/idlcxx/Generate.cmake
This commit allows to use generic function from cyclonedds repo
instead of implementing almost the same thing in this repo again.
Signed-off-by: Matija Tudan <tudan.matija@gmail.com>
> idlcxx: use idlc_generate() function from CycloneDDS package

- src/ddscxx/tests/Topic.cpp
- src/ddscxx/tests/data/RegressionModels.idl
- src/ddscxx/tests/data/Space.idl
- src/idlcxx/src/streamers.c
- src/idlcxx/src/traits.c
Add support for unions as topics
Add support for nested/topic annotations
> Union as topic and nested annotations

- src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/cdr_enums.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/topic/TopicTraits.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
- src/ddscxx/src/org/eclipse/cyclonedds/sub/BuiltinSubscriberDelegate.cpp
- src/ddscxx/tests/CMakeLists.txt
- src/ddscxx/tests/Regression.cpp
- src/ddscxx/tests/Serdata.cpp
- src/ddscxx/tests/Topic.cpp
- src/ddscxx/tests/data/TraitsModels.idl
- src/idlcxx/src/traits.c
> Add setting of allowed encodings through datarepresentation annotation

- .azure/templates/build-test.yml
> Use cyclonedds releases/0.9.x branch in CI

- src/ddscxx/tests/Regression.cpp
- src/ddscxx/tests/data/RegressionModels.idl
- src/idlcxx/src/streamers.c
Fix typedefs not being parsed correctly in the cases of multiple levels of typedef
> Typedef fixes

- CMakeLists.txt
> Bump version to 0.10.0

- src/ddscxx/tests/Regression.cpp
- src/ddscxx/tests/data/RegressionModels.idl
- src/idlcxx/src/generator.c
- src/idlcxx/src/streamers.c
Backports (well, cherry-picking) of recent commits that I believe ought to also be in the 0.9.0 release.
> Update for 0.9.0rc1

- src/ddscxx/src/org/eclipse/cyclonedds/core/cdr/cdr_stream.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/cdr/extended_cdr_v2_ser.cpp
- src/idlcxx/src/streamers.c
Fixes for the following coverity issues:
374419
374404
390111
> Coverity fixes

- src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/entity_properties.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/extended_cdr_v2_ser.hpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/cdr/cdr_stream.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/cdr/extended_cdr_v1_ser.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/cdr/extended_cdr_v2_ser.cpp
- src/ddscxx/tests/CDRStreamer.cpp
- src/ddscxx/tests/Regression.cpp
- src/ddscxx/tests/data/RegressionModels.idl
- src/idlcxx/src/streamers.c
- src/idlcxx/src/types.c
Fix a number of (possible) issues reported by coverity
> Coverity fix

- src/ddscxx/src/org/eclipse/cyclonedds/sub/BuiltinSubscriberDelegate.cpp
This fixes a compile error described in #279
closes #279
> fix specialization in different namespace

- src/ddscxx/include/dds/topic/detail/ContentFilteredTopic.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
- src/ddscxx/tests/SharedMemory.cpp
> Update the SHM data path with content filtered topics

- CMakeLists.txt
> Bump version number

- conanfile.txt
- src/ddscxx/include/dds/core/TInstanceHandle.hpp
- src/ddscxx/include/dds/core/detail/TInstanceHandleImpl.hpp
Workaround for the issues #162 and #252
> workaround issues 162 and 252

- docs/manual/howtos/exchange.rst
- docs/manual/howtos/listener.rst
- docs/manual/howtos/qos.rst
- docs/manual/howtos/status.rst
- docs/manual/howtos/waitset.rst
- docs/manual/idlcxx.rst
Various edits to the how-to guides to aid readability etc.
> Edits to the how-to guides

- src/idlcxx/src/generator.c
Fix for issue #367 @trittsv, could you give this a look and check whether it fixes the issue on your side?
> Fix for issue #367

- src/ddscxx/include/dds/core/TQosProvider.hpp
- src/ddscxx/include/dds/domain/TDomainParticipant.hpp
- src/ddscxx/include/dds/pub/DataWriter.hpp
- src/ddscxx/include/dds/pub/TAnyDataWriter.hpp
- src/ddscxx/include/dds/pub/TPublisher.hpp
- src/ddscxx/include/dds/pub/discovery.hpp
- src/ddscxx/include/dds/sub/TAnyDataReader.hpp
- src/ddscxx/include/dds/sub/TDataReader.hpp
- src/ddscxx/include/dds/sub/TSubscriber.hpp
- src/ddscxx/include/dds/sub/discovery.hpp
- src/ddscxx/src/org/eclipse/cyclonedds/core/ReportUtils.cpp
This PR removes all explicit mentions of vortex opensplice.
closes #347
Signed-off-by: Sven Trittler <sven.trittler@icloud.com>
> remove vortex opensplice leftovers

- src/idlcxx/src/types.c
This adds forward declarations in header files generated by the IDL compiler C++ backend. See also https://github.com/eclipse-cyclonedds/cyclonedds/pull/1593
Fixes https://github.com/eclipse-cyclonedds/cyclonedds-cxx/issues/371
> Fix idlcxx for forward declared types

- .azure/templates/build-test.yml
- CMakeLists.txt
- src/ddscxx/include/dds/pub/detail/DataWriterImpl.hpp
- src/ddscxx/include/dds/sub/detail/TDataReaderImpl.hpp
- src/ddscxx/include/dds/topic/detail/TTopicImpl.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/cdr_stream.hpp
- src/ddscxx/src/org/eclipse/cyclonedds/domain/DomainParticipantDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/pub/PublisherDelegate.cpp
- src/ddscxx/src/org/eclipse/cyclonedds/sub/SubscriberDelegate.cpp
- src/ddscxx/tests/CMakeLists.txt
- src/ddscxx/tests/DeferredDestruction.cpp
- src/idlcxx/src/generator.c
... plus backport of
* fix for crashes in some cases where destruction is delayed because of refcounting
* fix for listeners not being installed correctly if set in constructor
> Bump version number to 0.10.3

- src/ddscxx/src/org/eclipse/cyclonedds/pub/AnyDataWriterDelegate.cpp
- src/idlcxx/src/traits.c
Fixes #397
@reicheratwork would be willing to review this?
> Take inheritance into account for isKeyless trait

- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
link to the issue: https://github.com/eclipse-cyclonedds/cyclonedds-cxx/issues/407
> fix shm deserialize data error for those data with no fixed size

- src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
This explains the choices causing the confusion in issue #415
> Added more code comments to explain "weird" choices

- src/idlcxx/src/generator.c
except branch idl_is_type_spec(node)
As you say, change a fix way~ @eboasson
> repair issue #461

- CMakeLists.txt
Update version to 0.10.5 to match with the c repo.
> update version to 0.10.5

- CMakeLists.txt
> Correctly names CMake version configuration file 

- src/ddscxx/tests/Qos.cpp
Companion to https://github.com/eclipse-cyclonedds/cyclonedds/pull/2158
> Update test now that max PSMX Instances is gt 1

- .azure/coverity-scan.yml
- azure-pipelines.yml
- src/ddscxx/include/dds/core/macros.hpp
- src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/cdr_stream.hpp
- src/ddscxx/src/org/eclipse/cyclonedds/sub/cond/ReadConditionDelegate.cpp
- src/ddscxx/tests/External.cpp
Bump ubuntu to 24.04
Remove ubuntu 20.04 as this runner is no longer supported
Bump windows to 2022 and MSVC to 17
> Bump azure runner versions

- src/ddscxx/tests/Listener.cpp
- src/ddscxx/tests/WaitSet.cpp
Companion to eclipse-cyclonedds/cyclonedds#2255
> Update to match ddsrt_cond_... interface change
